# Generated by Django 4.2.30 on 2026-08-30 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_cartitem_negotiated_price_cartitem_negotiation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('refund_processing', 'Refund Processing'), ('refunded', 'Refunded')], default='paid', max_length=18),
        ),
    ]
