# Generated by Django 4.2.30 on 2026-08-30 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_cartitem_size_orderitem_size'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cartitem',
            name='unique_user_cart_item',
        ),
        migrations.RemoveConstraint(
            model_name='cartitem',
            name='unique_session_cart_item',
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'product', 'size'), name='unique_user_cart_item'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(condition=models.Q(('session_key__isnull', False)), fields=('session_key', 'product', 'size'), name='unique_session_cart_item'),
        ),
    ]
