# Generated by Django 4.2.30 on 2026-08-30 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topuprequest',
            name='provider',
            field=models.CharField(choices=[('gosentepay', 'GosentePay'), ('mtn_momo', 'MTN MoMo'), ('airtel_money', 'Airtel Money')], max_length=20),
        ),
    ]
