# Generated by Django 4.2.30 on 2026-08-30 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_cartitem_negotiated_price_cartitem_negotiation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallets', '0002_alter_topuprequest_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='type',
            field=models.CharField(choices=[('topup_gateway', 'Top-up via Gateway'), ('topup_via_agent_credit', 'Top-up via Agent (Credit)'), ('topup_via_agent_debit', 'Top-up via Agent (Debit)'), ('payment', 'Payment'), ('commission', 'Commission'), ('commission_reversal', 'Commission Reversal (Refund Clawback)'), ('refund', 'Refund'), ('adjustment', 'Adjustment')], max_length=30),
        ),
        migrations.CreateModel(
            name='RefundDisbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('external_reference', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('successful', 'Successful'), ('failed', 'Failed')], default='successful', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('initiated_by', models.ForeignKey(blank=True, help_text='The admin who issued this refund, if triggered manually rather than automatically.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds_issued', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='refund_disbursement', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
