# Generated by Django 4.2.30 on 2026-08-30 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0003_alter_wallettransaction_type_refunddisbursement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refunddisbursement',
            name='status',
            field=models.CharField(choices=[('successful', 'Successful'), ('failed', 'Failed'), ('disputed', 'Disputed — needs admin review')], default='successful', max_length=12),
        ),
    ]
