import requests
from django.conf import settings
from django.core.cache import cache

from .base import GatewayError, PaymentGateway

TOKEN_CACHE_KEY = "gosentepay_access_token"


class GosentePayGateway(PaymentGateway):
    """
    GosentePay unified collection/disbursement API — one gateway for
    both MTN and Airtel Uganda, replacing separate direct integrations
    with each network. Docs: https://gosentepay.com/developers

    Required settings: GOSENTEPAY_BASE_URL, GOSENTEPAY_API_KEY,
    GOSENTEPAY_SECRET_KEY, SITE_URL (for building the callback URL).

    Security note: GosentePay's own callback verification story is
    weak by design — it only suggests matching the `ref` field, which
    isn't signed or otherwise provable. Callers of this gateway must
    never trust a callback's body directly; always re-confirm via
    check_status() using our own authenticated token before crediting
    anything. See wallets/views.py's GatewayTopUpCallbackView, which
    already does exactly that.

    Every network call here is wrapped against requests.RequestException
    (DNS failures, timeouts, connection resets) and against malformed
    JSON responses — without this, a transient network hiccup (which
    this exact integration hit during real testing) surfaces as a raw
    500 with a full stack trace instead of the clean GatewayError ->
    ValidationError -> 400 response the rest of the app already
    expects and handles gracefully.
    """

    provider_name = 'gosentepay'

    def __init__(self):
        self.base_url = settings.GOSENTEPAY_BASE_URL.rstrip('/')
        self.api_key = settings.GOSENTEPAY_API_KEY
        self.secret_key = settings.GOSENTEPAY_SECRET_KEY

    def _post(self, path, **kwargs):
        """Shared request wrapper — every call site's network and
        JSON-parsing failures funnel through here into one place."""
        try:
            resp = requests.post(f"{self.base_url}{path}", **kwargs)
        except requests.RequestException as e:
            raise GatewayError(f"Could not reach GosentePay ({path}): {e}")
        return resp

    def _parse_json(self, resp, path):
        try:
            return resp.json()
        except ValueError:
            raise GatewayError(f"GosentePay returned non-JSON response from {path}: {resp.text[:300]}")

    def _get_access_token(self):
        """Bearer token via api_key, valid 24h. Cached until near expiry."""
        cached = cache.get(TOKEN_CACHE_KEY)
        if cached:
            return cached

        if not self.api_key:
            raise GatewayError("GOSENTEPAY_API_KEY is not configured.")

        resp = self._post(
            "/authorization_token",
            headers={"Content-Type": "application/json"},
            json={"api_key": self.api_key},
            timeout=15,
        )
        if resp.status_code != 200:
            raise GatewayError(f"GosentePay token request failed: {resp.status_code} {resp.text}")

        data = self._parse_json(resp, "/authorization_token")
        token = data.get("token")
        if not token:
            raise GatewayError(f"GosentePay token response missing 'token': {resp.text}")
        expires_in = int(data.get("expires_in", 86400))
        # Cache slightly under actual expiry so we never use a stale token.
        cache.set(TOKEN_CACHE_KEY, token, timeout=max(expires_in - 60, 60))
        return token

    def request_payment(self, phone_number: str, amount, external_id: str, email: str = None) -> str:
        if not self.secret_key:
            raise GatewayError("GOSENTEPAY_SECRET_KEY is not configured.")
        if not email:
            # GosentePay requires this on every deposit — unlike MTN/Airtel,
            # there's no way to omit it, so fail clearly rather than let
            # the provider reject it with a less helpful error.
            raise GatewayError("GosentePay requires a customer email for deposits.")

        token = self._get_access_token()
        callback_url = f"{settings.SITE_URL.rstrip('/')}/api/wallet/callback/gosentepay/"

        resp = self._post(
            "/deposit",
            headers={
                "Authorization": f"Bearer {token}",
                "Content-Type": "application/json",
            },
            json={
                "secret_key": self.secret_key,
                "phone": phone_number,
                "amount": str(amount),
                "email": email,
                # external_id is already a fresh uuid4 generated by
                # wallets.services.initiate_gateway_topup — reused
                # directly as GosentePay's own `ref`, since both just
                # need a caller-chosen, globally-unique identifier for
                # this transaction.
                "ref": external_id,
                "callback": callback_url,
            },
            timeout=20,
        )

        if resp.status_code == 409:
            raise GatewayError(f"GosentePay ref already used: {external_id}")
        if resp.status_code != 200:
            raise GatewayError(f"GosentePay deposit request failed: {resp.status_code} {resp.text}")

        data = self._parse_json(resp, "/deposit")
        if data.get("status") != "success":
            raise GatewayError(f"GosentePay deposit not accepted: {resp.text}")

        return external_id

    def check_status(self, reference_id: str) -> str:
        token = self._get_access_token()

        resp = self._post(
            "/transaction-status",
            headers={
                "Authorization": f"Bearer {token}",
                "Content-Type": "application/json",
            },
            json={"ref": reference_id},
            timeout=15,
        )
        if resp.status_code != 200:
            raise GatewayError(f"GosentePay status check failed: {resp.status_code} {resp.text}")

        data = self._parse_json(resp, "/transaction-status")
        provider_status = (data.get("transaction_status") or "").lower()
        mapping = {"pending": "pending", "successful": "successful", "failed": "failed"}
        return mapping.get(provider_status, "pending")

    def disburse(self, phone_number: str, amount, email: str, reason: str, external_id: str) -> str:
        """
        Sends money out of the business's GoSentePay balance to a
        customer's mobile wallet — used for refunds. Unlike deposits,
        this is NOT free: GoSentePay debits the amount plus a tiered
        fee (from UGX 1,100) up front, refunding both automatically if
        the transfer fails.

        The `callback` field here is speculative — GoSentePay's own
        documented fields for /withdraw don't list one (only /deposit
        does), so this may simply be ignored by their API. It costs
        nothing to include, and if their backend does support it even
        without documenting it, this gets the benefit for free. The
        synchronous response and /transaction-status polling remain
        the only mechanisms actually confirmed to work.
        """
        if not self.secret_key:
            raise GatewayError("GOSENTEPAY_SECRET_KEY is not configured.")
        if not email:
            raise GatewayError("GosentePay requires a recipient email for withdrawals.")

        token = self._get_access_token()
        callback_url = f"{settings.SITE_URL.rstrip('/')}/api/wallet/callback/gosentepay/"

        resp = self._post(
            "/withdraw",
            headers={
                "Authorization": f"Bearer {token}",
                "Content-Type": "application/json",
            },
            json={
                "secret_key": self.secret_key,
                "phone": phone_number,
                "amount": str(amount),
                "email": email,
                "reason": reason,
                "ref": external_id,
                "callback": callback_url,
            },
            timeout=20,
        )

        if resp.status_code == 409:
            raise GatewayError(f"GosentePay ref already used: {external_id}")
        if resp.status_code != 200:
            raise GatewayError(f"GosentePay withdrawal failed: {resp.status_code} {resp.text}")

        data = self._parse_json(resp, "/withdraw")
        if data.get("status") != "success":
            raise GatewayError(f"GosentePay withdrawal not accepted: {resp.text}")

        return external_id
