# Generated by Django 4.2.30 on 2026-08-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seller_floor',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Absolute minimum acceptable price during negotiation. Must be at least MINIMUM_MARGIN_PERCENT above cost_price. Never shown to customers.', max_digits=12, null=True),
        ),
    ]
