# Generated by Django 4.2.30 on 2026-08-30 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_product_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('clothes', 'Clothes'), ('trousers', 'Trousers'), ('shoes', 'Shoes'), ('accessories', 'Accessories'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
