# Generated by Django 4.2.30 on 2026-08-27 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_product_seller_floor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_velocity', models.FloatField(default=0, help_text='Units sold per day, recent window')),
                ('demand_score', models.FloatField(default=0, help_text='0-1, derived from views/cart-adds/sales')),
                ('inventory_pressure', models.FloatField(default=0, help_text='0-1, higher = lower stock relative to demand')),
                ('exchange_rate_signal', models.FloatField(default=0, help_text='-1 to 1, UGX/USD movement adjustment')),
                ('seasonal_signal', models.FloatField(default=0, help_text='-1 to 1, bounded seasonal demand adjustment')),
                ('calculated_market_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('confidence', models.FloatField(default=0, help_text='0-1 — how much real data backs this snapshot')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_snapshots', to='catalog.product')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='NegotiationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('agreed', 'Agreed'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('abandoned', 'Abandoned')], default='active', max_length=12)),
                ('agreed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('agreed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('market_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='negotiations', to='negotiations.marketsnapshot')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negotiations', to='catalog.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='negotiations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NegotiationOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn_type', models.CharField(choices=[('customer_offer', 'Customer Offer'), ('ai_response', 'AI Response')], max_length=15)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('decision', models.CharField(blank=True, choices=[('ACCEPT', 'Accept'), ('COUNTER', 'Counter'), ('REJECT', 'Reject')], max_length=10)),
                ('message', models.TextField(blank=True)),
                ('raw_ai_output', models.JSONField(blank=True, default=dict)),
                ('ai_proposed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('was_backend_overridden', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('market_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='negotiations.marketsnapshot')),
                ('negotiation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='negotiations.negotiationsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='negotiationsession',
            constraint=models.CheckConstraint(check=models.Q(('user__isnull', False), ('session_key__isnull', False), _connector='OR'), name='negotiation_has_owner'),
        ),
    ]
